name: My First Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2007692@ds.study.iitm.ac.in
        run: echo "Hello, world!"
