name: Cache Demo Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm 
          key: cache-7d72a8a
          restore-keys: |
            cache-7d72a8a
      
      - name: prime-cache-7d72a8a
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" == "true" ]; then
            echo "Cache Hit! 🎉"
          else
            echo "Cache Miss! ⚠️"
          fi
      
      - name: Install dependencies (if cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
